Algoritmo "Sucessor"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costas
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : André Luiz Da Silva Santos
// Data atual  : 17/03/2025
Var
   valor, sucessor: inteiro
Inicio
 
   escreva("Digite um valor: ")
   leia(valor)


   sucessor <- valor + 1

   escreval("O sucessor de ", valor, " é ", sucessor)

Fimalgoritmo
