Algoritmo "Area_Circulo"
// Disciplina   :Lógica de Programação com VisualG
// Professor   : Jailson Costa
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : André Luiz Da Silva Santos
// Data atual  : 17/03/2025
var
   raio, area, pi: real
inicio
   pi <- 3.1415
   escreva("Digite o raio do círculo: ")
   leia(raio)
   area <- pi * (raio * raio)
   escreva("Área do Círculo: ", area)
fimalgoritmo
