algoritmo "Area_Quadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2025

var
   lado, area: real
inicio
   escreva("Digite o lado do quadrado: ")
   leia(lado)
   area <- lado * lado
   escreva("Área do Quadrado: ", area)
fimalgoritmo
