Algoritmo "QuadradosDe15a200"
// Disciplina    Lógica de Programação
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2025
Var
   numero: inteiro
   quadrado: inteiro
Inicio
   para numero de 15 ate 200 faca
      quadrado <- numero * numero
      escreval("O quadrado de ", numero, " é ", quadrado)
   fimpara
Fimalgoritmo