Algoritmo "Soma100PrimeirosInteiros"
// Disciplina    Lógica de Programação
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2025
Var
   contador, soma: inteiro

Inicio
   soma <- 0

   para contador de 1 ate 100 faca
      soma <- soma + contador
   fimpara

   escreval("A soma dos 100 primeiros números inteiros é: ", soma)
Fimalgoritmo