Algoritmo "ParOuImpar"
// Disciplina    Lógica de Programação
// Professor   : Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2025
var
   numero: inteiro
inicio
      Escreva("Digite um número inteiro: ")
      Leia(numero)

      Se numero % 2 = 0 entao
         Escreva("O número ", numero, " é PAR")
      Senao
         Escreva("O número ", numero, " é ÍMPAR")
      FimSe
fimalgoritmo