Algoritmo "NumerosPares"
// Disciplina    Lógica de Programação
// Professor   : Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : André Luiz Da Silva Santos
// Data atual  : 24/03/2025
var
    numero: inteiro
inicio
    numero <- 2
    enquanto numero <= 20 faca
        se numero % 2 = 0 entao
            escreva(numero, " ")
        fimse
        numero <- numero + 1
    fimenquanto
fimalgoritmo