Algoritmo "L03D"
// Disciplina    Lógica de Programação
// Professor   : Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2025

var
    contador: inteiro
inicio
    contador <- 0
    
    enquanto contador <= 20 faca

        se contador % 2 <> 0 entao
            escreva(contador, " ")
        fimse
        contador <- contador + 1
    fimenquanto
fimalgoritmo