Algoritmo "QuadradosDe15a200"
// Disciplina    Lógica de Programação
// Professor   : Jailson Costas
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : André Luiz Da Silva Santos
// Data atual  : 07/04/2025

Var
   numero: inteiro
Inicio
   numero <- 15
   repita
      escreval(numero, "² = ", numero * numero)
      numero <- numero + 1
   ate numero > 200
Fimalgoritmo